apiVersion: v1
kind: Service
metadata:
  name: squire-web
  namespace: squire
  labels:
    app.kubernetes.io/name: squire-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: squire
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: squire-web
    app.kubernetes.io/component: web
